version: 2
jobs:
  build_ui:
    machine:
      image: ubuntu-2004:202111-01
    resource_class: arm.medium
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: |
          docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD
          docker buildx build --platform linux/arm/v7 -t cecchisandrone/smarthome-ui:latest --push ./smarthome-ui
      - persist_to_workspace:
          root: /home/circleci
          paths:
            - project/*
  build_server:
    machine:
      image: ubuntu-2004:202111-01
    resource_class: arm.medium
    working_directory: /tmp/project/smarthome-server
    steps:
      - attach_workspace:
          at: /tmp
      - run: |
          docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD
          docker buildx build --platform linux/arm/v7 -t cecchisandrone/smarthome-server:latest --push .
  build_images:
    machine:
      image: ubuntu-2004:202111-01
    resource_class: arm.medium
    working_directory: /tmp/project
    steps:
      - attach_workspace:
          at: /tmp
      - run: |
          docker login -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD
          docker buildx build --platform linux/arm/v7 -t cecchisandrone/prometheus:latest --push ./prometheus
          docker buildx build --platform linux/arm/v7 -t cecchisandrone/alertmanager:latest --push ./alertmanager
          docker buildx build --platform linux/arm/v7 -t cecchisandrone/blackbox-exporter:latest --push ./blackbox-exporter
  deploy:
    machine:
      image: ubuntu-2004:202111-01
    working_directory: /tmp/project
    steps:
      - attach_workspace:
          at: /tmp
      - run:
          command: scp -v -o StrictHostKeyChecking=no -P $SMARTHOME_SSH_PORT docker-compose.yml pi@$SMARTHOME_SSH_HOST:/home/pi
      - run:
          command: ssh -o StrictHostKeyChecking=no -l pi $SMARTHOME_SSH_HOST -p $SMARTHOME_SSH_PORT "docker-compose stop && docker-compose pull && docker-compose up -d"
          no_output_timeout: 30m
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_ui
      - build_server:
          requires:
            - build_ui
      - build_images:
          requires:
            - build_ui
      - deploy:
          requires:
            - build_ui
            - build_server
            - build_images