version: 2
jobs:
  build:
    docker:
      - image: node:6.12.1
    steps:
      - checkout
          post:
          - git submodule sync --recursive
          - git submodule update --recursive --init
      - run: pwd
      - run: ls
      - run: cd smarthome-ui && npm install
      - run: cd smarthome-ui && npm run build
      - persist_to_workspace:
          root: /root
          paths:
            - project/*
  deploy:
    machine:
      enabled: true
    working_directory: /tmp/project
    steps:
      - attach_workspace:
          at: /tmp
      - run: |
          pwd
          ls
          docker login repo.treescale.com -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD
          docker build -t repo.treescale.com/cecchisandrone/smarthome-ui:latest smarthome-ui
          docker build -t repo.treescale.com/cecchisandrone/smarthome-server:latest smarthome-server
          docker push repo.treescale.com/cecchisandrone/smarthome-ui:latest
          docker push repo.treescale.com/cecchisandrone/smarthome-server:latest
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build