version: 2
jobs:
  build:
    machine: true
    steps:
    - checkout
    - run: |
        docker login repo.treescale.com -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD
        docker build -t repo.treescale.com/cecchisandrone/smarthome-ui:latest smarthome-ui
        docker build -t repo.treescale.com/cecchisandrone/smarthome-server:latest smarthome-server
        docker push repo.treescale.com/cecchisandrone/smarthome-ui:latest
        docker push repo.treescale.com/cecchisandrone/smarthome-server:latest
    - run: echo Deploy