version: 2
jobs:                
  build:
    working_directory: ~/smarthome
    steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Install Docker client
        command: |
            set -x
            VER="17.09.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin    
    - run: docker login repo.treescale.com -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD
    - run: |
        docker build -t repo.treescale.com/cecchisandrone/smarthome-ui:latest smarthome-ui
        docker build -t repo.treescale.com/cecchisandrone/smarthome-server:latest smarthome-server
        docker push repo.treescale.com/cecchisandrone/smarthome-ui:latest
        docker push repo.treescale.com/cecchisandrone/smarthome-server:latest
    - run: echo Deploy