version: 2
jobs:
  build_ui:
    machine:
      enabled: true
    steps:
      - checkout
      - run: git submodule sync
      - run: git submodule update --init
      - run: |
          cd smarthome-ui
          docker build -t smarthome-ui:build .
          id=$(docker create smarthome-ui:build)
          docker cp $id:/build/dist .
          docker build -f Dockerfile-runtime -t repo.treescale.com/cecchisandrone/smarthome-ui:latest . 
          docker login repo.treescale.com -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD
          docker push repo.treescale.com/cecchisandrone/smarthome-ui:latest
      - persist_to_workspace:
          root: /root
          paths:
            - project/*
  build_server:
    machine: 
      enabled: true
    working_directory: /tmp/project/smarthome-server
    steps:
      - attach_workspace:
          at: /tmp
      - run: |
          docker build -t smarthome-server:build .
          docker images
          id=$(docker create smarthome-server:build)
          docker cp $id:/go/src/github.com/cecchisandrone/smarthome-server/smarthome-server .
          docker build -f Dockerfile-runtime -t repo.treescale.com/cecchisandrone/smarthome-server:latest . 
          docker login repo.treescale.com -u $DOCKER_REGISTRY_USERNAME -p $DOCKER_REGISTRY_PASSWORD
          docker push repo.treescale.com/cecchisandrone/smarthome-server:latest
  deploy:
    machine:
      enabled: true
    working_directory: /tmp/project
    steps:
      - run:
          command: ssh -o StrictHostKeyChecking=no -l pi $SMARTHOME_SSH_HOST -p $SMARTHOME_SSH_PORT "docker-compose stop && docker-compose pull && docker-compose up"
          no_output_timeout: 30m
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build_ui
      - build_server:
          requires:
            - build_ui
      - deploy:
          requires:
            - build_ui
            - build_server