global:
  scrape_interval:     10s
  evaluation_interval: 10s
  scrape_timeout:      10s
rule_files:
  - 'alert.rules'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: "icmp"
    scrape_interval: 7200s
    scrape_timeout: 10s
    metrics_path: "/probe"
    params:
      module: [ping]
    static_configs:
      # Router
      - targets: ['192.168.1.1']
        labels:
          role: 'router'
          name: 'Fritz Box 7590'
      - targets: ['192.168.1.2']
        labels:
          role: 'router'
          name: 'Netgear N300'
      - targets: ['192.168.1.4']
        labels:
          role: 'router'
          name: 'Tp-Link TD-W8901G'
      - targets: ['192.168.1.5']
        labels:
          role: 'router'
          name: 'Fritz Box 7170'
      - targets: ['192.168.1.6']
        labels:
          role: 'router'
          name: 'Netgear R6220'
      - targets: ['192.168.1.7']
        labels:
          role: 'router'
          name: 'Tp-Link TL-WR841N'
      - targets: ['192.168.1.13']
        labels:
          role: 'router'
          name: 'BBOX'
      - targets: ['192.168.1.21']
        labels:
          role: 'router'
          name: 'Technicolor'
      - targets: ['192.168.1.23']
        labels:
          role: 'router'
          name: 'Technicolor'
      - targets: ['192.168.1.24']
        labels:
          role: 'router'
          name: 'Router TIM'
      - targets: ['192.168.1.25']
        labels:
          role: 'router'
          name: 'TP-Link CPE210 AP'
      - targets: ['192.168.1.26']
        labels:
          role: 'router'
          name: 'TP-Link CPE210 Client'  
      - targets: ['192.168.1.142']
        labels:
          role: 'router'
          name: 'TP-Link Extender'
      # Camera
      - targets: ['192.168.1.11']
        labels:
          role: 'camera'
          name: 'Entrance'
      - targets: ['192.168.1.12']
        labels:
          role: 'camera'
          name: 'External'
      - targets: ['192.168.1.14']
        labels:
          role: 'camera'
          name: 'Basement'
      - targets: ['192.168.1.15']
        labels:
          role: 'camera'
          name: 'Living'
      - targets: ['192.168.1.17']
        labels:
          role: 'camera'
          name: 'Gate'
      - targets: ['192.168.1.16']
        labels:
          role: 'camera'
          name: 'Parkway'
      # IOT
      - targets: ['192.168.1.19']
        labels:
          role: 'iot'
          name: 'RaspberryPi Zero W'
      - targets: ['192.168.1.101']
        labels:
          role: 'iot'
          name: 'Roborock S5 Max'
      - targets: ['192.168.1.105']
        labels:
          role: 'iot'
          name: 'Inverter monitor'
      - targets: ['192.168.1.112']
        labels:
          role: 'iot'
          name: 'WDTVLive'
      - targets: ['192.168.1.120']
        labels:
          role: 'iot'
          name: 'Weather station'
      - targets: ['192.168.1.124']
        labels:
          role: 'iot'
          name: 'Well pump'
      - targets: ['192.168.1.132']
        labels:
          role: 'iot'
          name: 'Power monitor'
      - targets: ['192.168.1.141']
        labels:
          role: 'iot'
          name: 'Basement pump'
      - targets: ['192.168.1.166']
        labels:
          role: 'iot'
          name: 'Lights Relay'
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115  # Blackbox exporter.

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets:
      - "alertmanager:9093"
